Covid19System/Covid19System/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^about/$', views.about),
    path('', views.home, name="home"),
    path('', include('authentication.urls')),
    path('MOH/', include('MedicalOfficerOfHealth.urls')),
    path('normal_user/', include('NormalUser.urls')),
    path('sys_admin/', include('system_admin.urls')),
 ]

Covid19System/NormalUser/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # path('upldprovincels/', views.uploadProvinceCityWardList, name="upload_province_city_ward_list"),
    path('', views.home_normal_user, name='home_normal_user'),
    path('profile/', views.profile, name='profile'),
    path('editprofile/', views.edit_profile, name='edit_profile'),
    path('kbyt/', views.medical_declaration, name='medical_declaration'),
    path('showkbytlist/', views.show_kbyt_list, name='show_kbyt_list'),
    path('showkbytdetail/<int:id>', views.show_kbyt_detail, name='show_kbyt_detail'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-wards/', views.load_wards, name='ajax_load_wards'),
]

Covid19System/NormalUser/models.py
from django.db import models
from authentication.models import User
from django.utils import timezone

# Create your models here.
class Province(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class City(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Ward(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class NormalUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    DoB = models.DateField('Date of Birth', blank=True, null=True)

    GENDER_CHOICE = (
        ('M', 'Nam'),
        ('F', 'Nữ'),
        ('O', 'Khác')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE) # 3 values: M - male, F -female, O - others
    phone_number = models.CharField(max_length=10)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    ward = models.ForeignKey(Ward, on_delete=models.SET_NULL, blank=True, null=True)
    detailed_address = models.CharField(max_length=500)


class MedicalDeclaration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    declarationTime = models.DateTimeField(default=timezone.now, blank=False, null=False)

    registerForOtherPeople = models.BooleanField(default=False)
    full_name = models.CharField(max_length=50)
    id_card = models.CharField(max_length=12)
    year_of_birth = models.CharField(max_length=20)
    GENDER_CHOICE = (
        ('Nam', 'Nam'),
        ('Nữ', 'Nữ'),
        ('Khác', 'Khác')
    )
    gender = models.CharField(max_length=4, choices=GENDER_CHOICE)
    nationality = models.CharField(max_length=20)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    ward = models.ForeignKey(Ward, on_delete=models.SET_NULL, blank=True, null=True)
    detailed_address = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=10)
    email = models.CharField(max_length=50)
    BOOLEAN_CHOICE = (
        ('Không', 'Không'),
        ('Có', 'Có')
    )
    past_14d_travel = models.CharField(max_length=6, choices=BOOLEAN_CHOICE, default=BOOLEAN_CHOICE[0][0])
    arrival_province = models.ForeignKey(Province, related_name='arrival_province', on_delete=models.SET_NULL, blank=True, null=True)
    arrival_city = models.ForeignKey(City, related_name='arrival_city', on_delete=models.SET_NULL, blank=True, null=True)
    arrival_ward = models.ForeignKey(Ward, related_name='arrival_ward', on_delete=models.SET_NULL, blank=True, null=True)
    arrival_detailed_place = models.CharField(max_length=500, blank=True, null=True)

    past_14d_symptoms = models.CharField(max_length=6, choices=BOOLEAN_CHOICE, default=BOOLEAN_CHOICE[0][0])
    deltaild_description = models.CharField(max_length=5000, blank=True, null=True)

    in_contact_confirmed_COVID19_case = models.CharField(max_length=6, choices=BOOLEAN_CHOICE, default=BOOLEAN_CHOICE[0][0])
    in_contact_people_from_countries_with_COVID19 = models.CharField(max_length=6, choices=BOOLEAN_CHOICE, default=BOOLEAN_CHOICE[0][0])
    in_contact_people_with_syptoms = models.CharField(max_length=6, choices=BOOLEAN_CHOICE, default=BOOLEAN_CHOICE[0][0])

Covid19System/NormalUser/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from django.http import JsonResponse
import pandas as pd


import qrcode
import qrcode.image.svg
from io import BytesIO

from MedicalOfficerOfHealth.models import CovidCertificate
from .forms import MedicalDeclarationForm, NormalUserInfoForm
from .models import MedicalDeclaration, NormalUser, Province, City, Ward
# Create your views here.
def normal_check(user):
    return user.is_normal_user

@login_required(login_url='/login')
@user_passes_test(normal_check, login_url='/')
def home_normal_user(request):
    current_user = request.user
    no_of_vaccination = 0
    try:
        check = CovidCertificate.objects.get(pk=current_user.username)
        no_of_vaccination = check.no_of_vaccination 
    except CovidCertificate.DoesNotExist:
        pass
    qr_dict = 'Họ & Tên: ' + current_user.last_name + ' ' + current_user.first_name + '\n' + 'CCCD: ' + current_user.username + '\n' + 'Số mũi vắc xin đã tiêm: ' + str(no_of_vaccination)
    factory = qrcode.image.svg.SvgImage
    img = qrcode.make(qr_dict, image_factory=factory, version=5)
    stream = BytesIO()
    img.save(stream)
    svg = stream.getvalue().decode()
    return render(request, 'home_normal_user.html', {'svg': svg})

def profile(request):
    if request.user.is_authenticated and request.user.is_normal_user is True:
        current_user = request.user

        no_of_vaccination = 0
        try:
            check = CovidCertificate.objects.get(pk=current_user.username)
            no_of_vaccination = check.no_of_vaccination 
        except CovidCertificate.DoesNotExist:
            pass

        try:
            detail_info = NormalUser.objects.get(pk=current_user)
        except:
            normalUser = NormalUser(user=current_user)
            normalUser.save()

        detail_info = NormalUser.objects.get(pk=current_user)

        qr_dict = 'Họ & Tên: ' + current_user.last_name + ' ' + current_user.first_name + '\n' + 'CCCD: ' + current_user.username + '\n' + 'Số mũi vắc xin đã tiêm: ' + str(no_of_vaccination)
        factory = qrcode.image.svg.SvgImage
        img = qrcode.make(qr_dict, image_factory=factory, version=5)
        stream = BytesIO()
        img.save(stream)
        svg = stream.getvalue().decode()
        return render(request, 'profile.html', {'current_user': current_user, 'detail_info': detail_info, 'no_of_vaccination': no_of_vaccination, 'svg': svg})
    elif request.user.is_authenticated and request.user.is_normal_user is False:
        return redirect('home')
    return redirect('login')


def edit_profile(request):
    if request.user.is_authenticated and request.user.is_normal_user is True:
        current_user = request.user

        try:
            person = NormalUser.objects.get(pk=current_user)
        except:
            normalUser = NormalUser(user=current_user)
            normalUser.save()

        person = NormalUser.objects.get(pk=current_user)

        form = NormalUserInfoForm()
        try:
            form = NormalUserInfoForm(instance=person)
        except:
            form =NormalUserInfoForm()
        if request.method == 'POST':
            fname = request.POST.get('fname')
            lname = request.POST.get('lname')
            current_user.last_name = lname
            current_user.first_name = fname
            current_user.save()
            form = NormalUserInfoForm(request.POST, instance=person)

            if form.is_valid() :
                form.save()
                messages.success(request, 'Cập nhật thông tin!')
                return redirect('edit_profile')

        return render(request, 'edit_profile.html', {'form': form, 'current_user': current_user})
    elif request.user.is_authenticated and request.user.is_normal_user is False:
        return redirect('home')
    return redirect('login')

def medical_declaration(request):
    if request.user.is_authenticated and request.user.is_normal_user is True:
        current_user = request.user
        form = MedicalDeclarationForm()
        if request.method == 'POST':
            newMedicalDeclaration = MedicalDeclaration(user=current_user)
            # time = newMedicalDeclaration.declarationTime
            newMedicalDeclaration.save()
            # newMedicalDeclaration = MedicalDeclaration.objects.get(user=current_user, declarationTime=time)
            form = MedicalDeclarationForm(request.POST, instance=newMedicalDeclaration)


            if form.is_valid() :
                form.save()
                messages.success(request, 'Khai báo y tế thành công!')
                return redirect('medical_declaration')

        return render(request, 'medical_declaration.html', {'form': form, 'current_user': current_user})
    elif request.user.is_authenticated and request.user.is_normal_user is False:
        return redirect('home')
    return redirect('login')


def show_kbyt_list(request):
    if request.user.is_authenticated and request.user.is_normal_user is True:
        current_user = request.user
        # MedicalDeclaration.objects.filter(full_name="").delete()
        medicalDeclarationList = MedicalDeclaration.objects.filter(user=current_user)
        for medicalDeclaration in medicalDeclarationList:
            print(str(medicalDeclaration.declarationTime))
        ls = {
            "data": medicalDeclarationList
        }
        return render(request, 'medical_declaration_list.html', ls)
    elif request.user.is_authenticated and request.user.is_normal_user is False:
        return redirect('home')
    return redirect('login')


def show_kbyt_detail(request, id):
    if request.user.is_authenticated and request.user.is_normal_user is True:
        current_user = request.user
        print(id)
        medicalDeclaration = MedicalDeclaration.objects.get(pk=id)

        return render(request, 'medical_declaration_detail.html', {'medicalDeclaration': medicalDeclaration})
    elif request.user.is_authenticated and request.user.is_normal_user is False:
        return redirect('home')
    return redirect('login')


# AJAX
def load_cities(request):
    province_id = request.GET.get('province_id')
    cities = City.objects.filter(province_id=province_id).all()
    return render(request, 'city_dropdown_list_options.html', {'cities': cities})

def load_wards(request):
    city_id = request.GET.get('city_id')
    wards = Ward.objects.filter(city_id=city_id).all()
    return render(request, 'ward_dropdown_list_options.html', {'wards': wards})


# def uploadProvinceCityWardList(request):
#     thx_list = pd.read_excel('D:\OneDrive - Hanoi University of Science and Technology\Web technologies and e-Services\web-project\doc\TinhHuyenXa2021.xlsx')
#     province_list = thx_list['Tỉnh Thành Phố'].unique()

#     for index, row in thx_list.iterrows():
#         try:
#             province = Province.objects.get(name=row['Tỉnh Thành Phố'])
#         except:
#             new_entry = Province(name = row['Tỉnh Thành Phố'])
#             new_entry.save()
#             print(row['Tỉnh Thành Phố'])

#         province = Province.objects.get(name=row['Tỉnh Thành Phố'])
#         try:
#             city = City.objects.get(province=province, name=row['Quận Huyện'])
#         except:
#             new_entry = City(province=province, name = row['Quận Huyện'])
#             new_entry.save()

#         city = City.objects.get(province=province, name=row['Quận Huyện'])
#         try:
#             ward = Ward.objects.get(city=city, name = row['Phường Xã'])
#         except:
#             new_entry = Ward(city=city, name = row['Phường Xã'])
#             new_entry.save()

  
#     return redirect('home')

Covid19System/NormalUser/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

Covid19System/NormalUser/templates/edit_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'edit_profile_style.css'%}">
    <script src="{% static 'normal_user_script.js'%}"></script>
    <title>Điều chỉnh thông tin cá nhân</title>
</head>
<body>
    {% if user.is_authenticated and user.is_normal_user is True %}
    <nav>
        <div class="logo">
          <h4>Covid System</h4>
        </div>
        <div class="nav-links">
          <button class="home-button" onclick="home()"><i class="fas fa-home" style="margin-right: 7px;"></i>Trang chủ</button>
          <button class="button" onclick="about()">Thông tin</button>
          <button class="login-button" onclick="signout()">Đăng xuất</button>
        </div>
      </nav>
    <main>
        <div class="form-container">
            <h3>Thông tin cá nhân</h3>
            
            <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" data-wards-url="{% url 'ajax_load_wards' %}">
                {% csrf_token %}
                <div class="start">
                    <div class="group">
                        <label for="lanme" class="label">Họ</label>
                        <input id="lname" name="lname" type="text" class="input" value="{{ current_user.last_name }}" Required>
                    </div>
                    <div class="group">
                        <label for="fanme" class="label">Tên đệm & Tên</label>
                        <input id="fname" name="fname" type="text" class="input" value="{{ current_user.first_name }}" Required>
                    </div>
                    <div class="group">
                        <label for="DoB" class="label">Ngày sinh</label>
                        {{ form.DoB }}
                        
                    </div>
                    <div class="group">
                        <label for="gender" class="label">Giới tính</label>
                        
                        {{ form.gender }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="phone" class="label">Điện thoại</label>
                        
                        {{ form.phone_number }}
                    </div>
                </div>
                <div class="end">
                    <h3>Địa chỉ nơi ở hiện tại</h3>
                    <div class="group">
                        <label for="province" class="label">Tỉnh thành </label>
                        {{ form.province }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="city" class="label">Quận / huyện </label>
                        {{ form.city }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="ward" class="label">Phường / xã</label>
                        {{ form.ward }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="detailed_address" class="label">Số nhà, phố, tổ dân phố/thôn/đội</label>
                        {{ form.detailed_address }}
                    </div>
                    <br/>
                    <input class="submit" type="submit" value="Lưu thay đổi">
                    {% include 'messages.html' %}
                </div>
            </form>
        </div>
    </main>
    
    <div class="planet Earth">
        <div class="container">
            <div class="loader"><span></span></div>
            <div class="earth"></div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_province").change(function () {
            const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
            const provinceId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'province_id': provinceId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    <script>
        $("#id_city").change(function () {
            const url = $("#personForm").attr("data-wards-url");  // get the url of the `load_cities` view
            const cityId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'city_id': cityId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_ward").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    {% elif user.is_authenticated and user.is_normal_user is False %}
    <script>window.location.href = 'http://127.0.0.1:8000'</script>
    {% else %}
    <script>window.location.href = 'http://127.0.0.1:8000/login'</script>
    {% endif %}
</body>
</html>

Covid19System/NormalUser/templates/medical_declaration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'medical_declaration_style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossorigin="anonymous"/>
    <script src="{% static 'normal_user_script.js'%}"></script>
    <title>Khai báo y tế</title>
</head>
<body>
    <nav>
        <div class="logo">
            <h4>Covid System</h4>
        </div>
        <div class="nav-links">
            <button class="home-button" onclick="home()"><i class="fas fa-home" style="margin-right: 7px;"></i>Trang chủ</button>
            <button class="button" onclick="about()">Thông tin</button>
            <button class="login-button" onclick="signout()">Đăng xuất</button>
        </div>
    </nav>
    <main>
        {% if user.is_authenticated and user.is_normal_user is True %}
        <div class="form-container">
            <h2>Khai báo y tế</h2>
            
            <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" data-wards-url="{% url 'ajax_load_wards' %}">
                {% csrf_token %}
                <div class="start">
                    <div class="group">
                        <label for="registerForOtherPeople" class="label">Khai hộ</label>
                        {{ form.registerForOtherPeople }}
                        
                    </div>
                    <div class="group">
                        <label for="full_name" class="label">Họ tên (ghi chữ IN HOA)</label>
                        {{ form.full_name }}
                    </div>
                    <div class="group">
                        <label for="id_card" class="label">Số CCCD</label>
                        {{ form.id_card }}
                    </div>
                    <div class="group">
                        <label for="year_of_birth" class="label">Năm sinh</label>
                        {{ form.year_of_birth }}
                    </div>
                    <div class="group">
                        <label for="gender" class="label">Giới tính</label>
                        {{ form.gender }}
                    </div>
                    <div class="group">
                        <label for="nationality" class="label">Quốc tịch</label>
                        {{ form.nationality }}
                    </div>
                    <br/>
                    
                    
                    <h4>Địa chỉ liên lạc tại Việt Nam</h4>
                    <div class="group">
                        <label for="province" class="label">Tỉnh thành </label>
                        {{ form.province }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="city" class="label">Quận / huyện </label>
                        {{ form.city }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="ward" class="label">Phường / xã</label>
                        {{ form.ward }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="detailed_address" class="label">Số nhà, phố, tổ dân phố/thôn/đội</label>
                        {{ form.detailed_address }}
                    </div>
                    <br/>
                    <div class="group">
                        <label for="phone_number" class="label">Điện thoại</label>
                        {{ form.phone_number }}
                    </div>
                    <div class="group">
                        <label for="email" class="label">Email</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="end">
                    <div class="group">
                        <label for="past_14d_travel" class="label">Trong vòng 14 ngày qua, Anh/Chị có đến tỉnh/thành phố, quốc gia/vùng lãnh thổ nào</label>
                        {{ form.past_14d_travel }}
                    </div>
                    <div class="arr_addr" hidden="true">
                        <h4>Nơi đến</h4>
                        <div class="group">
                            <label for="arrival_province" class="label">Tỉnh thành</label>
                            {{ form.arrival_province }}
                        </div>
                        <div class="group">
                            <label for="arrival_city" class="label">Quận / huyện</label>
                            {{ form.arrival_city }}
                        </div>
                        <div class="group">
                            <label for="arrival_ward" class="label">Phường / xã</label>
                            {{ form.arrival_ward }}
                        </div>
                        <div class="group">
                            <label for="arrival_detailed_place" class="label">Số nhà, phố, tổ dân phố/thôn/đội</label>
                            {{ form.arrival_detailed_place }}
                        </div>
                    </div>
                    
                    <div class="group">
                        <label for="past_14d_symptoms" class="label">Trong vòng 14 ngày qua, Anh/Chị có thấy xuất hiện ít nhất 1 trong các dấu hiệu: sốt, ho, khó thở, viêm phổi, đau họng, mệt mỏi không?</label>
                        {{ form.past_14d_symptoms }}
                    </div>
                    <div class="group symptoms_deltail" hidden="true">
                        <label for="deltaild_description" class="label">Mô tả chi tiết</label>
                        {{ form.deltaild_description }}
                    </div>
                    <div>
                        <h4>Trong vòng 14 ngày qua, Anh/Chị có tiếp xúc với</h4>
                        
                        <div class="group">
                            <label for="in_contact_confirmed_COVID19_case" class="label">Người bệnh hoặc nghi ngờ, mắc bệnh COVID-19 </label>
                            {{ form.in_contact_confirmed_COVID19_case }}
                        </div>
                        <div class="group">
                            <label for="in_contact_people_from_countries_with_COVID19" class="label">Người từ nước có bệnh COVID-19 </label>
                            {{ form.in_contact_people_from_countries_with_COVID19 }}
                        </div>
                        <div class="group">
                            <label for="in_contact_people_with_syptoms" class="label">Người có biểu hiện (Sốt, ho, khó thở , Viêm phổi) </label>
                            {{ form.in_contact_people_with_syptoms }}
                        </div>
                    </div>
                    <input class="submit" type="submit" value="Lưu thay đổi">
                    {% include 'messages.html' %}
                </div>
            </form>
        </div>
    </main>
    
    <div class="planet Earth">
        <div class="container">
            <div class="loader"><span></span></div>
            <div class="earth"></div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $(function() {
            $('#arr_addr_1').click(function() {
                $('.arr_addr').attr('hidden',false);
            });           
            $('#arr_addr_0').click(function() {
                $('.arr_addr').attr('hidden',true);
                $('.arrival').val("");
            });
        });
    </script>
    <script>
        $(function() {
            $('#symptoms_deltail_1').click(function() {
                $('.symptoms_deltail').attr('hidden',false);
            });           
            $('#symptoms_deltail_0').click(function() {
                $('.symptoms_deltail').attr('hidden',true);
                $('#id_deltaild_description').val("");
            });
        });
    </script>
    <script>
        $("#id_province").change(function () {
            const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
            const provinceId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'province_id': provinceId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    <script>
        $("#id_city").change(function () {
            const url = $("#personForm").attr("data-wards-url");  // get the url of the `load_cities` view
            const cityId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'city_id': cityId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_ward").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    <script>
        $("#id_arrival_province").change(function () {
            const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
            const provinceId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'province_id': provinceId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_arrival_city").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    <script>
        $("#id_arrival_city").change(function () {
            const url = $("#personForm").attr("data-wards-url");  // get the url of the `load_cities` view
            const cityId = $(this).val();  // get the selected country ID from the HTML input
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'city_id': cityId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_arrival_ward").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
            
        });
    </script>
    {% elif user.is_authenticated and user.is_normal_user is False %}
    <script>window.location.href = 'http://127.0.0.1:8000'</script>
    {% else %}
    <script>window.location.href = 'http://127.0.0.1:8000/login'</script>
    {% endif %}
</body>
</html>

Covid19System/NormalUser/templates/ward_dropdown_list_options.html
<option value="">---------</option>
{% for ward in wards %}
<option value="{{ ward.pk }}">{{ ward.name }}</option>
{% endfor %}